-- Add many more style tags for users to choose from
INSERT INTO public.style_tags (name, name_es) VALUES
-- More general styles
('Korean Style', 'Estilo Coreano'),
('Y2K', 'Y2K'),
('Streetwear', 'Streetwear'),
('UK Drill', 'UK Drill'),
('Hypebeast', 'Hypebeast'),
('Grunge', 'Grunge'),
('Goth', 'Gótico'),
('Punk', 'Punk'),
('Cottagecore', 'Cottagecore'),
('Dark Academia', 'Academia Oscura'),
('Light Academia', 'Academia Clara'),
('Old Money', 'Old Money'),
('Quiet Luxury', 'Lujo Silencioso'),
('Athleisure', 'Athleisure'),
('Sporty', 'Deportivo'),
('Preppy', 'Preppy'),
('Coastal Grandmother', 'Abuela Costera'),
('Barbiecore', 'Barbiecore'),
('Coquette', 'Coquette'),
('Mob Wife', 'Mob Wife'),
('Clean Girl', 'Clean Girl'),
('Tomboy', 'Tomboy'),
('Androgynous', 'Andrógino'),
('Soft Boy', 'Soft Boy'),
('E-Boy', 'E-Boy'),
('E-Girl', 'E-Girl'),
('Skater', 'Skater'),
('Surfer', 'Surfero'),
('Hippie', 'Hippie'),
('Retro', 'Retro'),
('70s Disco', 'Disco 70s'),
('80s Power', 'Power 80s'),
('90s Grunge', 'Grunge 90s'),
('Techwear', 'Techwear'),
('Cyberpunk', 'Cyberpunk'),
('Futuristic', 'Futurista'),
('Normcore', 'Normcore'),
('Gorpcore', 'Gorpcore'),
('Workwear', 'Workwear'),
('Utility', 'Utilitario'),
('Military', 'Militar'),
('Safari', 'Safari'),
('French Chic', 'Chic Francés'),
('Italian Style', 'Estilo Italiano'),
('Scandinavian', 'Escandinavo'),
('Japanese Minimal', 'Minimalismo Japonés'),
('Artsy', 'Artístico'),
('Creative', 'Creativo'),
('Bold', 'Atrevido'),
('Colorful', 'Colorido'),
('Monochrome', 'Monocromático'),
('All Black', 'Todo Negro'),
('Neutral Tones', 'Tonos Neutros'),
('Earthy', 'Terroso'),
('Pastel', 'Pastel'),
('Neon', 'Neón'),
('Luxe', 'Lujoso'),
('High Fashion', 'Alta Moda'),
('Avant Garde', 'Avant Garde'),
('Eclectic', 'Ecléctico'),
('Mix & Match', 'Mezcla'),
('Layered', 'Con Capas'),
('Oversized', 'Oversize'),
('Fitted', 'Ajustado'),
('Relaxed', 'Relajado'),
('Formal', 'Formal'),
('Smart Casual', 'Smart Casual'),
('Business', 'Negocios'),
('Evening Wear', 'Ropa de Noche'),
('Party', 'Fiesta'),
('Festival', 'Festival'),
('Cozy', 'Acogedor'),
('Comfy', 'Cómodo'),
('Sustainable', 'Sostenible'),
('Thrift', 'Segunda Mano'),
('Indie', 'Indie'),
('Alt', 'Alternativo'),
('Baddie', 'Baddie'),
('Soft Girl', 'Soft Girl'),
('Balletcore', 'Balletcore'),
('Tenniscore', 'Tenniscore')
ON CONFLICT DO NOTHING;

-- Add more predefined categories with is_top/is_bottom flags
INSERT INTO public.categories (user_id, name, name_es, is_top, is_bottom)
SELECT 
  u.id,
  c.name,
  c.name_es,
  c.is_top,
  c.is_bottom
FROM auth.users u
CROSS JOIN (VALUES
  ('T-Shirt', 'Camiseta', true, false),
  ('Shirt', 'Camisa', true, false),
  ('Blouse', 'Blusa', true, false),
  ('Sweater', 'Suéter', true, false),
  ('Hoodie', 'Sudadera', true, false),
  ('Jacket', 'Chaqueta', true, false),
  ('Coat', 'Abrigo', true, false),
  ('Blazer', 'Blazer', true, false),
  ('Cardigan', 'Cárdigan', true, false),
  ('Tank Top', 'Camiseta de Tirantes', true, false),
  ('Crop Top', 'Crop Top', true, false),
  ('Vest', 'Chaleco', true, false),
  ('Polo', 'Polo', true, false),
  ('Jeans', 'Vaqueros', false, true),
  ('Pants', 'Pantalones', false, true),
  ('Shorts', 'Shorts', false, true),
  ('Skirt', 'Falda', false, true),
  ('Dress', 'Vestido', true, true),
  ('Jumpsuit', 'Mono', true, true),
  ('Leggings', 'Leggings', false, true),
  ('Joggers', 'Joggers', false, true),
  ('Trousers', 'Pantalones de Vestir', false, true),
  ('Chinos', 'Chinos', false, true),
  ('Cargo Pants', 'Pantalones Cargo', false, true),
  ('Sweatpants', 'Pantalón Deportivo', false, true),
  ('Sneakers', 'Zapatillas', false, false),
  ('Boots', 'Botas', false, false),
  ('Heels', 'Tacones', false, false),
  ('Sandals', 'Sandalias', false, false),
  ('Loafers', 'Mocasines', false, false),
  ('Hat', 'Sombrero', false, false),
  ('Cap', 'Gorra', false, false),
  ('Beanie', 'Gorro', false, false),
  ('Scarf', 'Bufanda', false, false),
  ('Belt', 'Cinturón', false, false),
  ('Watch', 'Reloj', false, false),
  ('Necklace', 'Collar', false, false),
  ('Bracelet', 'Pulsera', false, false),
  ('Ring', 'Anillo', false, false),
  ('Earrings', 'Pendientes', false, false),
  ('Sunglasses', 'Gafas de Sol', false, false),
  ('Bag', 'Bolso', false, false),
  ('Backpack', 'Mochila', false, false)
) AS c(name, name_es, is_top, is_bottom)
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories cat 
  WHERE cat.user_id = u.id AND cat.name = c.name
);

-- Add onboarding_completed field to profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS year_of_birth INTEGER;